import { config } from './config.js';
import { normalizeBatch, mergeSamples } from './data.js';
import { storage } from './storage.js';

const $ = (s,root=document)=>root.querySelector(s);
const app = $('#app'), modal=$('#modal');
const localApi = Boolean(config.apiBase && ['127.0.0.1','localhost','[::1]'].includes(new URL(config.apiBase,location.href).hostname));
const escape = value => String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={
 clock:'<circle cx="12" cy="12" r="8.5"/><path d="M12 7v5l3 2"/>',
 hourglass:'<path d="M7 3h10M7 21h10M8 3v4c0 3 8 7 8 10v4M16 3v4c0 3-8 7-8 10v4"/>',
 minimal:'<path d="M8 3H3v5M16 3h5v5M21 16v5h-5M8 21H3v-5"/><path d="M8 8h8v8H8z"/>',
 expand:'<path d="M3 8V3h5M16 3h5v5M21 16v5h-5M8 21H3v-5M3 3l5 5M21 3l-5 5M21 21l-5-5M3 21l5-5"/>',
 volume:'<path d="M11 5 6 9H3v6h3l5 4zM15 8a6 6 0 0 1 0 8M18 5a10 10 0 0 1 0 14"/>',
 mute:'<path d="M11 5 6 9H3v6h3l5 4zM16 9l5 6M21 9l-5 6"/>',
 help:'<circle cx="12" cy="12" r="9"/><path d="M9.5 9a2.5 2.5 0 1 1 3 2.5c-.5.2-.5 1-.5 1.5M12 17h.01"/>',
 logout:'<path d="M9 4H5a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h4M10 12h11M17 8l4 4-4 4"/>',
 close:'<path d="m6 6 12 12M18 6 6 18"/>',
 eye:'<path d="M2 12s4-6 10-6 10 6 10 6-4 6-10 6S2 12 2 12"/><circle cx="12" cy="12" r="2.5"/>',
 camera:'<rect x="3" y="5" width="13" height="14" rx="3"/><path d="m16 9 5-3v12l-5-3"/>',
 wrist:'<rect x="7" y="6" width="10" height="12" rx="3"/><path d="m9 6 1-4h4l1 4M9 18l1 4h4l1-4M10 12h4"/>',
 send:'<path d="m3 3 18 9-18 9 3-9-3-9zM6 12h15"/>',
 lock:'<rect x="5" y="10" width="14" height="11" rx="3"/><path d="M8 10V7a4 4 0 0 1 8 0v3M12 14v3"/>',
};
const icon=(name)=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${paths[name]??paths.clock}</svg>`;
const whale=()=>'<img class="deepseek" src="deepseek.svg" alt="" aria-hidden="true"/>';
const words={
 zh:{working:'专注进行中',current:'当前时间',elapsed:'已工作',session:'本次专注',minimal:'极简模式',full:'完整模式',sound:'通知声音',language:'语言',help:'帮助与数据',logout:'退出登录',camera:'摄像头指数',wrist:'手环指数',measure:'需要休息的概率',waitingCamera:'等待摄像头数据',waitingWrist:'等待手环数据',noSource:'尚未连接',last:'最新窗口',time:'时间',minutes:'分钟',local:'本地预览模式',clockHint:'安心专注，适时休息。',clockHint2:'你的节奏，由你掌握。',companion:'YOUR FOCUS COMPANION',assistant:'专注助手',unconnected:'API 尚未连接',chatTitle:'随时聊聊你的状态',chatBody:'连接 DeepSeek 后，助手将每分钟读取两项指数，并在合适的时候提醒你休息。',chatPlaceholder:'告诉我你正在做什么…',chatFoot:'对话仅保存在此浏览器',notBuilt:'功能尚未实现',apiMessage:'DeepSeek API 尚未接入。你的消息已在此浏览器保存，接入后即可发送。',close:'关闭',okay:'知道了',server:'云端账户和个人数据库尚未接入。当前账户与数据仅保存在此浏览器。',demo:'演示',demoText:'演示功能尚未实现。之后会将示例数据送入分析代码。',helpText:'横轴是窗口结束时间，纵轴是需要休息的概率（0–100%）。摄像头与手环分别显示；无效窗口保留空缺，不会当作 0%。',data:'查看与导入数据',dataText:'粘贴分析程序的 JSON 输出，可使用单个窗口、数组或 {"samples": [...]}。输入有效后，两条图表会更新。',import:'导入数据',importDone:'数据已导入',noData:'暂无数据',invalid:'输入无效',selectLanguage:'选择语言',missing:'暂未接入',sent:'待发送',logoutTitle:'退出本次专注？',logoutText:'本次计时将结束。图表和对话仍保存在此浏览器的个人账户中。',cancel:'取消',finish:'退出',sourceHint:'数据连接后显示实时指数',readOnly:'读取输出数据',displayed:'个窗口',startDate:'今天',review:'每分钟检查一次',pending:'已保存，等待 API 接入',network:'连接失败，请稍后重试',forgot:'密码找回服务尚未接入。',jd:'JD 登录尚未接入。'},
 en:{working:'Focus in progress',current:'Current time',elapsed:'Time working',session:'This session',minimal:'Minimal mode',full:'Full mode',sound:'Notification sound',language:'Language',help:'Help & data',logout:'Log out',camera:'Camera index',wrist:'Wrist index',measure:'Probability of needing rest',waitingCamera:'Waiting for camera data',waitingWrist:'Waiting for wrist data',noSource:'Not connected',last:'Latest window',time:'Time',minutes:'min',local:'Local prototype',clockHint:'A little focus. A little breathing room.',clockHint2:'Work at your own pace.',companion:'YOUR FOCUS COMPANION',assistant:'Focus assistant',unconnected:'API not connected',chatTitle:'A space to check in',chatBody:'Once connected, DeepSeek will read both indices every minute and can remind you when it is time for a break.',chatPlaceholder:'What are you working on?',chatFoot:'Chats stay in this browser',notBuilt:'Not implemented yet',apiMessage:'The DeepSeek API is not connected. Your message is saved in this browser and can be sent after integration.',close:'Close',okay:'Got it',server:'Cloud accounts and the personal database are not connected. This account and its data stay in this browser.',demo:'Demo',demoText:'The demo is not implemented yet. Later, sample data will be passed into the analysis code.',helpText:'The x-axis is the window end time. The y-axis is the probability of needing rest (0–100%). Camera and wrist are shown separately; invalid windows stay as gaps, rather than becoming 0%.',data:'View & import data',dataText:'Paste JSON output from the analysis code: one window, an array, or {"samples": [...]}. Valid input updates both charts.',import:'Import data',importDone:'Data imported',noData:'No data yet',invalid:'Invalid input',selectLanguage:'Choose language',missing:'Not connected yet',sent:'Pending',logoutTitle:'End this focus session?',logoutText:'The timer will end. Charts and chats will stay with your personal account in this browser.',cancel:'Cancel',finish:'Log out',sourceHint:'Indices will appear when data is connected',readOnly:'View output data',displayed:'windows',startDate:'Today',review:'Checked every minute',pending:'Saved, waiting for API integration',network:'Connection failed. Please try again.',forgot:'Password recovery is not implemented yet.',jd:'JD sign-in is not implemented yet.'}
};
let user=null,personal=null,route='login',chatOpen=false,unread=false,range=30,audio=null,observationBusy=false,lastNotice=null;
let toastTimer,saveChain=Promise.resolve();
const t=(key)=>words[personal?.language??'zh'][key]??key;
Object.assign(words.zh,{localService:'数据保存在本机',localServiceText:'网页在线加载，账户和数据保存在本机的 SQLite 数据库。请保持本地服务运行。',localChat:'对话保存在本机',helper:'连接本地服务'});
Object.assign(words.en,{localService:'Data stored on this computer',localServiceText:'The website loads online. Accounts and data are stored in SQLite on this computer. Keep the local helper running.',localChat:'Chats stay on this computer',helper:'Connect local service'});
const lang=()=>personal?.language==='en'?'en-GB':'zh-CN';
function notify(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3200);}
function save(){if(!personal)return Promise.resolve();const snapshot=structuredClone(personal);saveChain=saveChain.then(()=>config.apiBase?requestApi('/v1/preferences',{language:snapshot.language,sound:snapshot.sound,sessionStarted:snapshot.sessionStarted??null}):storage.savePersonal(snapshot)).catch(()=>notify('Unable to save changes.'));return saveChain;}
function dialog(title,body,actions=''){if(modal.open)modal.close();$('#modal-content').innerHTML=`<div class="modal-inner"><div class="modal-header"><h2 id="modal-title">${escape(title)}</h2><button class="close-button" data-action="close-modal" aria-label="${t('close')}">${icon('close')}</button></div>${body}<div class="modal-actions">${actions||`<button class="primary" data-action="close-modal">${t('okay')}</button>`}</div></div>`;modal.showModal();}
function unavailable(message){dialog(t('notBuilt'),`<p class="modal-text">${escape(message)}</p>`);}
function localSetup(){
 const publicOrigin=location.protocol==='https:'?location.origin:'https://YOUR-NAME.github.io';
 const command=`python3 server.py --port 8000 --origin ${publicOrigin}`;
 dialog('Connect this computer',`<p class="modal-text">Start the helper in the extracted rest-time folder. Your accounts and data will be stored on this computer. Then return to this online page and log in. Allow local-network access if your browser asks.</p><pre class="setup-command">${escape(command)}</pre><p class="modal-text">No cloud account server is required. Keep the helper running during use.</p>`);
}
function setRoute(next){location.hash=next;}
function auth(signup=false){
 document.documentElement.lang='en';
 const field=(name,label,type='text',autocomplete='')=>`<label class="field" for="${name}">${label}<span class="input-wrap"><input id="${name}" name="${name}" type="${type}" autocomplete="${autocomplete}" required ${name==='password'?'minlength="8" maxlength="128" data-password':name==='confirm'?'minlength="8" maxlength="128" data-password':'maxlength="120"'} placeholder="${name==='identity'?'Enter your username or email':name==='name'?'Your name':name==='confirm'?'Re-enter your password':'Enter your password'}" />${type==='password'?`<button type="button" class="password-toggle" data-action="show-password" data-target="${name}" aria-label="Show password">${icon('eye')}</button>`:''}</span></label>`;
 return `<main class="blue-screen"><img class="auth-corner" src="logo.png" alt="Rest Time logo"/><section class="auth-card" aria-labelledby="auth-title"><h1 id="auth-title" class="auth-title">Rest Time</h1><p class="auth-greeting">${signup?'Create your account':'Welcome Back!'}</p><form class="auth-form" id="auth-form" data-signup="${signup}">${signup?field('name','Name','text','name'):''}${field('identity','Username / Email','text','username')}${field('password','Password','password',signup?'new-password':'current-password')}${signup?field('confirm','Confirm Password','password','new-password'):''}<p class="form-error" id="auth-error" role="alert"></p><button class="primary auth-submit" type="submit">${signup?'Sign In':'Log in'}</button>${signup?'':'<button type="button" class="text-button forgot" data-action="forgot">Forgot Password</button>'}</form><div class="separator"><span>or</span></div><button class="secondary jd-button" data-action="jd"><span class="jd-mark" aria-hidden="true">JD</span>Continue with JD</button><p class="auth-switch">${signup?'Already with Rest Time? <a href="#login">Log In</a>':'New to Rest Time? <a href="#signup">Sign In</a>'}</p><p class="local-note">${localApi?'Accounts and data stay on this computer':config.apiBase?'Connected account server':'Browser-local prototype'}</p>${localApi?'<button class="text-button local-setup-button" data-action="local-setup">Connect local service</button>':''}</section><span class="auth-footer">REST TIME / A LITTLE BREATHING ROOM</span></main>`;
}
function welcome(){return `<main class="blue-screen"><img class="auth-corner" src="logo.png" alt="Rest Time logo"/><section class="welcome"><button class="start-button" data-action="start" aria-label="Start a focus session"><img src="logo.png" alt=""/></button><h1>Welcome Back.</h1><p>Ready to Start?</p><div class="eyebrow">REST TIME</div></section><button class="welcome-logout" data-action="logout-welcome">${t('logout')}</button></main>`;}
function tool(name,label,action,selected=false){return `<button class="tool ${selected?'selected':''}" data-action="${action}" aria-label="${escape(label)}" data-tip="${escape(label)}" ${action==='sound'?`aria-pressed="${personal.sound}"`:action==='mode'?`aria-pressed="${route==='minimal'}"`:''}>${name==='language'?'<span class="language-icon" aria-hidden="true">中 / A</span>':icon(name)}</button>`;}
function sidebar(){return `<aside class="sidebar" aria-label="Rest Time tools"><button class="assistant-button" data-action="chat" aria-label="DeepSeek ${t('assistant')}" aria-pressed="${chatOpen}" title="DeepSeek">${whale()}<span class="notification-dot ${unread?'unread':''}" aria-hidden="true"></span></button><div class="side-rule"></div>${tool(route==='minimal'?'expand':'minimal',route==='minimal'?t('full'):t('minimal'),'mode',route==='minimal')}${tool(personal.sound?'volume':'mute',t('sound'),'sound')}${tool('language',t('language'),'language')}${tool('help',t('help'),'help')}<div class="sidebar-bottom"><span class="avatar" title="${escape(user.name)}">${escape(user.name.slice(0,1).toUpperCase())}</span>${tool('logout',t('logout'),'logout')}</div></aside>`;}
function timePart(working=false){return `<div class="time-part"><div class="time-label">${icon(working?'hourglass':'clock')}${t(working?'elapsed':'current')}</div><div class="time-value ${working?'work-time':''}" data-time="${working?'elapsed':'current'}">00:00<span class="seconds">00</span></div><div class="time-sub">${working?t('session'):new Date().toLocaleDateString(lang(),{month:'long',day:'numeric',weekday:'short'})}</div></div>`;}
function graph(kind){return `<section class="chart-card ${kind}" aria-labelledby="${kind}-heading"><div class="chart-top"><h2 class="chart-name" id="${kind}-heading"><span class="chart-icon">${icon(kind)}</span>${t(kind)}</h2><div class="chart-score" data-score="${kind}">—<span>%</span></div></div><div class="chart-meta"><span>${t('measure')}</span><select data-range="${kind}" aria-label="${t('time')}">${[15,30,60].map(v=>`<option value="${v}" ${range===v?'selected':''}>${v} ${t('minutes')}</option>`).join('')}</select></div><div class="chart-frame" data-frame="${kind}"><svg class="plot" viewBox="0 0 520 145" role="img" aria-label="${t(kind)}: ${t('measure')}" data-chart="${kind}"></svg><div class="empty-chart" data-empty="${kind}">${t(kind==='camera'?'waitingCamera':'waitingWrist')}</div><div class="chart-tooltip" data-tooltip="${kind}" hidden></div></div><div class="chart-foot"><span class="chart-key">${t('last')}</span><span data-last="${kind}">${t('noSource')}</span></div></section>`;}
function chat(){return `<section class="chat-panel" aria-label="DeepSeek ${t('assistant')}"><header class="chat-head"><div><div class="chat-brand">${whale()}DeepSeek</div><div class="chat-badge">${t('unconnected')}</div></div><button class="close-button" data-action="chat" aria-label="${t('close')}">${icon('close')}</button></header><div class="chat-messages" id="chat-messages">${chatMessages()}</div><div class="chat-input"><form id="chat-form"><label for="chat-message" class="eyebrow" style="position:absolute;clip-path:inset(50%);width:1px;height:1px;overflow:hidden">${t('chatPlaceholder')}</label><textarea id="chat-message" name="message" placeholder="${t('chatPlaceholder')}" maxlength="4000" required></textarea><button type="submit" class="send-button" aria-label="Send message">${icon('send')}</button></form><div class="chat-disclaimer">${localApi?t('localChat'):config.apiBase?'DeepSeek':t('chatFoot')}</div></div></section>`;}
function chatMessages(){return personal.messages.length?personal.messages.map(m=>`<div class="message ${m.role==='assistant'?'assistant':''} ${m.pending?'pending':''}">${escape(m.content)}${m.pending?`<div class="message-meta">${t('pending')}</div>`:''}</div>`).join(''):`<div class="chat-empty">${whale()}<strong>${t('chatTitle')}</strong>${t('chatBody')}</div>`;}
function workspace(){const mini=route==='minimal';return `<div class="workspace ${mini?'minimal':''} ${chatOpen?'chat-open':''}">${sidebar()}<main class="main"><header class="workspace-header"><div class="brand">Rest Time</div><div class="session-label">${icon('hourglass')}${t('working')}</div><div class="header-date">${new Date().toLocaleDateString(lang(),{month:'short',day:'numeric',weekday:'long'})}</div></header>${mini?`<div class="minimal-layout"><div class="minimal-chat">${chatOpen?chat():''}</div><section class="minimal-clock" aria-label="${t('session')}">${timePart()}<div class="minimal-divider"></div>${timePart(true)}<div class="minimal-caption">REST TIME / ${t('companion')}</div></section></div>`:`<div class="work-layout">${chatOpen?chat():`<section class="companion-panel"><img class="companion-logo" src="logo.png" alt="Rest Time logo"/><p class="companion-copy">${t('clockHint')}<br/>${t('clockHint2')}</p><div class="companion-bottom"><span class="quiet-line"></span>${t('companion')}</div></section>`}<section class="data-side" aria-label="Focus session data"><div class="time-card">${timePart()}${timePart(true)}</div>${graph('camera')}${graph('wrist')}</section></div>`}<footer class="work-footer"><span>${t('sourceHint')}</span><span class="local-pill">${icon('lock')}${localApi?t('localService'):config.apiBase?escape(user.identity):t('local')}</span></footer></main></div>`;}
function render(){const next=location.hash.slice(1)||'login';route=['login','signup','welcome','active','minimal'].includes(next)?next:'login';if(['welcome','active','minimal'].includes(route)&&!user){route='login';history.replaceState(null,'','#login');}if(['active','minimal'].includes(route)&&!personal.sessionStarted){route='welcome';history.replaceState(null,'','#welcome');}document.title=`Rest Time${route==='minimal'?' · Minimal':route==='active'?' · Focus':''}`;document.documentElement.lang=route==='login'||route==='signup'||route==='welcome'?'en':personal?.language==='en'?'en':'zh-CN';app.innerHTML=route==='signup'?auth(true):route==='login'?auth():route==='welcome'?welcome():workspace();updateClock();renderCharts();if(chatOpen){const box=$('#chat-messages');if(box)box.scrollTop=box.scrollHeight;}}
function duration(ms){const sec=Math.max(0,Math.floor(ms/1000));return [Math.floor(sec/3600),Math.floor(sec/60)%60,sec%60].map(v=>String(v).padStart(2,'0'));}
function updateClock(){if(!personal)return;const date=new Date();const current=[date.getHours(),date.getMinutes(),date.getSeconds()].map(v=>String(v).padStart(2,'0'));const elapsed=duration(Date.now()-(personal.sessionStarted??Date.now()));for(const kind of ['current','elapsed']){const node=$(`[data-time="${kind}"]`);if(node){const values=kind==='current'?current:elapsed;node.innerHTML=`${values[0]}:${values[1]}<span class="seconds">${values[2]}</span>`;}}}
function timeLabel(timestamp){return new Date(timestamp).toLocaleTimeString(lang(),{hour:'2-digit',minute:'2-digit',hour12:false});}
function chartWindow(){const newest=personal.samples.at(-1);const end=newest?Date.parse(newest.timestamp):Date.now();return {end,start:end-range*60_000};}
function renderCharts(){if(!personal||route!=='active')return;const {end,start}=chartWindow();for(const kind of ['camera','wrist']){const node=$(`[data-chart="${kind}"]`);if(!node)continue;const key=kind==='camera'?'camera_index':'wrist_index';const rows=personal.samples.filter(r=>Date.parse(r.timestamp)>=start&&Date.parse(r.timestamp)<=end);const valid=rows.filter(r=>r[key]!==null);const color=kind==='camera'?'#3979ed':'#1ba1a6';const x=ts=>38+(Date.parse(ts)-start)/(end-start)*468;const y=v=>114-v/100*99;let segments=[],segment=[];for(const row of rows){if(row[key]===null){if(segment.length)segments.push(segment);segment=[];}else segment.push([x(row.timestamp),y(row[key])]);}if(segment.length)segments.push(segment);const grid=[0,25,50,75,100].map(v=>`<line x1="38" x2="506" y1="${y(v)}" y2="${y(v)}" stroke="#eaf0f7" ${v>0&&v<100?'stroke-dasharray="3 4"':''}/><text x="27" y="${y(v)+4}" text-anchor="end">${v}</text>`).join('');const ticks=[0,1,2,3].map(i=>{const stamp=start+(end-start)*i/3;return `<text x="${38+468*i/3}" y="138" text-anchor="${i===0?'start':i===3?'end':'middle'}">${timeLabel(stamp)}</text>`;}).join('');const areas=segments.filter(s=>s.length>1).map(s=>`<path d="M${s[0][0]},114 L${s.map(p=>p.join(',')).join(' L')} L${s.at(-1)[0]},114Z" fill="url(#fill-${kind})"/>`).join('');const lines=segments.map(s=>`<path d="M${s.map(p=>p.join(',')).join(' L')}" fill="none" stroke="${color}" stroke-width="2.5" stroke-linejoin="round" stroke-linecap="round"/>`).join('');const last=valid.at(-1);const lastRow=rows.at(-1);node.innerHTML=`<defs><linearGradient id="fill-${kind}" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="${color}" stop-opacity=".14"/><stop offset="100%" stop-color="${color}" stop-opacity="0"/></linearGradient></defs>${grid}${ticks}${areas}${lines}${last?`<circle cx="${x(last.timestamp)}" cy="${y(last[key])}" r="6" fill="${color}" opacity=".12"/><circle cx="${x(last.timestamp)}" cy="${y(last[key])}" r="3" fill="${color}" stroke="#fff" stroke-width="1.5"/>`:''}<line data-crosshair x1="0" x2="0" y1="15" y2="114" stroke="${color}" stroke-dasharray="3 3" opacity="0"/>`;
 const current=lastRow?.[key];$(`[data-score="${kind}"]`).innerHTML=`${current!=null?current.toFixed(0):'—'}<span>%</span>`;$(`[data-empty="${kind}"]`).hidden=Boolean(valid.length);$(`[data-last="${kind}"]`).textContent=lastRow?`${timeLabel(lastRow.timestamp)}${current==null?' · '+t('missing'):''}`:t('noSource');
 node.onpointermove=(event)=>{if(!rows.length)return;const rect=node.getBoundingClientRect();const requested=start+Math.max(0,Math.min(1,((event.clientX-rect.left)/rect.width*520-38)/468))*(end-start);const point=rows.reduce((a,b)=>Math.abs(Date.parse(a.timestamp)-requested)<Math.abs(Date.parse(b.timestamp)-requested)?a:b);const tooltip=$(`[data-tooltip="${kind}"]`);tooltip.hidden=false;tooltip.innerHTML=`${timeLabel(point.timestamp)}<br/><strong>${point[key]!=null?point[key].toFixed(1)+'%':t('missing')}</strong>`;tooltip.style.left=`${Math.min(rect.width-105,Math.max(12,(x(point.timestamp)/520)*rect.width-43))}px`;tooltip.style.top='15px';const cross=$('[data-crosshair]',node);cross.setAttribute('x1',x(point.timestamp));cross.setAttribute('x2',x(point.timestamp));cross.setAttribute('opacity','.35');};node.onpointerleave=()=>{$(`[data-tooltip="${kind}"]`).hidden=true;$('[data-crosshair]',node).setAttribute('opacity','0');};
}}
function openHelp(){dialog(t('help'),`<div class="help-block"><h3>${t('camera')} & ${t('wrist')}</h3><p class="modal-text">${t('helpText')}</p><div class="help-action"><button class="secondary" data-action="data">${t('data')}</button><button class="secondary" data-action="demo">${t('demo')}</button></div></div><div class="help-block"><h3>DeepSeek</h3><p class="modal-text">${t('chatBody')}</p></div><div class="help-block"><h3>${t(localApi?'localService':'local')}</h3><p class="modal-text">${t(localApi?'localServiceText':'server')}</p></div>`);}
function openData(){const example={window_end_utc:new Date().toISOString(),camera_result:{valid:true,need_rest_probability_percent:25,quality_score:0.9},physiology_result:{valid:true,need_rest_probability_percent:32,quality_score:0.9}};dialog(t('data'),`<p class="modal-text">${t('dataText')}</p><textarea class="modal-data" id="data-input" aria-label="Analysis JSON" spellcheck="false" placeholder="${escape(JSON.stringify(example,null,2))}">${personal.samples.length?escape(JSON.stringify({samples:personal.samples.slice(-60)},null,2)):''}</textarea><p class="form-error" id="data-error" role="alert"></p><p class="modal-text">${personal.samples.length} ${t('displayed')}</p>`,`<button class="secondary" data-action="close-modal">${t('close')}</button><button class="primary" data-action="import">${t('import')}</button>`);}
async function requestApi(path,body){let response;try{response=await fetch(config.apiBase.replace(/\/$/,'')+path,{...(localApi?{targetAddressSpace:'loopback'}:{}),method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...(sessionStorage.getItem('rt-token')?{Authorization:`Bearer ${sessionStorage.getItem('rt-token')}`}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});}catch(error){if(localApi)throw new Error('Cannot connect to the local service. Start the helper with this website’s origin and allow local-network access.');throw error;}const result=await response.json();if(!response.ok)throw new Error(result.error??`Request failed (${response.status})`);return result;}
async function authenticate(form){const data=new FormData(form);const signup=form.dataset.signup==='true';const submit=$('[type=submit]',form);$('#auth-error').textContent='';if(signup&&data.get('password')!==data.get('confirm')){$('#auth-error').textContent='Passwords do not match.';return;}if(!data.get('identity').trim()||(signup&&!data.get('name').trim())){$('#auth-error').textContent='Please complete all fields.';return;}submit.disabled=true;try{if(config.apiBase){const response=await requestApi(signup?'/v1/signup':'/v1/login',{identity:data.get('identity'),name:data.get('name'),password:data.get('password')});user=response.user;sessionStorage.setItem('rt-token',response.token);personal=response.personal;}else{user=signup?await storage.signup(data.get('name'),data.get('identity'),data.get('password')):await storage.login(data.get('identity'),data.get('password'));personal=await storage.personal(user.id);}sessionStorage.setItem('rt-user',JSON.stringify(user));personal.sessionStarted=null;await save();chatOpen=false;setRoute('welcome');}catch(error){$('#auth-error').textContent=error.message;}finally{submit.disabled=false;}}
async function sendMessage(form){const sendUser=user.id;const input=$('#chat-message');const content=input.value.trim();if(!content)return;const message={id:crypto.randomUUID(),role:'user',content,timestamp:new Date().toISOString(),pending:!config.apiBase};personal.messages.push(message);personal.messages=personal.messages.slice(-200);input.value='';await save();if(user?.id!==sendUser)return;$('#chat-messages').innerHTML=chatMessages();$('#chat-messages').scrollTop=$('#chat-messages').scrollHeight;if(!config.apiBase){unavailable(t('apiMessage'));return;}const submit=$('[type=submit]',form);submit.disabled=true;try{const response=await requestApi('/v1/chat',{message:content});if(user?.id!==sendUser)return;personal.profile=response.profile??personal.profile;if(response.reply)personal.messages.push({role:'assistant',content:response.reply,timestamp:new Date().toISOString()});await save();$('#chat-messages').innerHTML=chatMessages();$('#chat-messages').scrollTop=$('#chat-messages').scrollHeight;}catch(e){if(user?.id!==sendUser)return;message.pending=true;await save();$('#chat-messages').innerHTML=chatMessages();unavailable(e.message);}finally{submit.disabled=false;}}
function enableAudio(){if(!audio)audio=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume().catch(()=>{});}
function chime(){if(!personal.sound||!audio)return;try{for(const [i,f] of [740,988].entries()){const osc=audio.createOscillator(),gain=audio.createGain();osc.connect(gain);gain.connect(audio.destination);osc.frequency.value=f;const start=audio.currentTime+i*.15;gain.gain.setValueAtTime(0,start);gain.gain.linearRampToValueAtTime(.075,start+.015);gain.gain.exponentialRampToValueAtTime(.001,start+.32);osc.start(start);osc.stop(start+.34);}}catch{}}
function receiveNotification(message){if(!message?.id||message.id===lastNotice)return;lastNotice=message.id;personal.messages.push({id:message.id,role:'assistant',content:String(message.content??''),timestamp:message.timestamp??new Date().toISOString()});personal.messages=personal.messages.slice(-200);save();if(chatOpen){const box=$('#chat-messages');if(box){box.innerHTML=chatMessages();box.scrollTop=box.scrollHeight;}}else{unread=true;$('.notification-dot')?.classList.add('unread');}chime();}
async function observe(){if(!config.apiBase||!user||!['active','minimal'].includes(route)||observationBusy)return;observationBusy=true;const observedUser=user.id;try{const payload=await requestApi('/v1/data/latest');if(user?.id!==observedUser)return;if(payload.samples?.length){personal.samples=mergeSamples(personal.samples,normalizeBatch(payload.samples));await save();renderCharts();}const result=await requestApi('/v1/observe',{});if(user?.id!==observedUser)return;personal.profile=result.profile??personal.profile;if(result.notification)receiveNotification(result.notification);}catch(error){console.warn('Rest Time observation:',error.message);}finally{observationBusy=false;}}
async function logout(){if(config.apiBase){try{await requestApi('/v1/logout',{});}catch{}}if(personal){personal.sessionStarted=null;await save();}user=null;personal=null;unread=false;chatOpen=false;sessionStorage.removeItem('rt-user');sessionStorage.removeItem('rt-token');modal.close();setRoute('login');}
document.addEventListener('click',async event=>{const button=event.target.closest('[data-action]');if(!button)return;const action=button.dataset.action;if(['start','sound','chat'].includes(action)&&personal?.sound){try{enableAudio();}catch{}}switch(action){case 'close-modal':modal.close();break;case 'local-setup':localSetup();break;case 'show-password':{const input=$('#'+button.dataset.target);input.type=input.type==='password'?'text':'password';button.setAttribute('aria-label',input.type==='password'?'Show password':'Hide password');break;}case 'forgot':unavailable(t('forgot'));break;case 'jd':unavailable(t('jd'));break;case 'start':personal.sessionStarted=Date.now();await save();setRoute('active');observe();break;case 'mode':setRoute(route==='minimal'?'active':'minimal');break;case 'chat':chatOpen=!chatOpen;if(chatOpen)unread=false;render();if(chatOpen)$('#chat-message')?.focus();break;case 'sound':personal.sound=!personal.sound;if(personal.sound){try{enableAudio();}catch{}}await save();render();notify(personal.sound?(personal.language==='en'?'Sound on':'通知声音已开启'):(personal.language==='en'?'Sound off':'通知声音已关闭'));break;case 'language':dialog(t('selectLanguage'),`<div class="language-options"><button data-action="set-language" data-language="zh" class="${personal.language==='zh'?'selected':''}">简体中文</button><button data-action="set-language" data-language="en" class="${personal.language==='en'?'selected':''}">English</button></div>`);break;case 'set-language':personal.language=button.dataset.language;await save();modal.close();render();break;case 'help':openHelp();break;case 'demo':unavailable(t('demoText'));break;case 'data':openData();break;case 'import':try{const incoming=normalizeBatch(JSON.parse($('#data-input').value));if(config.apiBase)await requestApi('/v1/input',{samples:incoming});personal.samples=mergeSamples(personal.samples,incoming);await save();modal.close();renderCharts();notify(t('importDone'));}catch(e){$('#data-error').textContent=`${t('invalid')}: ${e.message}`;}break;case 'logout':dialog(t('logoutTitle'),`<p class="modal-text">${t('logoutText')}</p>`,`<button class="secondary" data-action="close-modal">${t('cancel')}</button><button class="primary" data-action="confirm-logout">${t('finish')}</button>`);break;case 'confirm-logout':case 'logout-welcome':await logout();break;}});
document.addEventListener('submit',event=>{if(event.target.id==='auth-form'){event.preventDefault();authenticate(event.target);}if(event.target.id==='chat-form'){event.preventDefault();sendMessage(event.target);}});
document.addEventListener('change',event=>{if(event.target.dataset.range){range=Number(event.target.value);for(const select of document.querySelectorAll('[data-range]'))select.value=range;renderCharts();}});
document.addEventListener('keydown',event=>{if(event.target.id==='chat-message'&&event.key==='Enter'&&!event.shiftKey&&!event.isComposing){event.preventDefault();event.target.form.requestSubmit();}});
modal.addEventListener('click',event=>{if(event.target===modal){const rect=modal.getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)modal.close();}});
window.addEventListener('hashchange',()=>{render();observe();});
document.addEventListener('visibilitychange',()=>{if(!document.hidden){updateClock();renderCharts();observe();}});
setInterval(updateClock,1000);setInterval(()=>{renderCharts();observe();},config.refreshMs);
try{const remembered=JSON.parse(sessionStorage.getItem('rt-user')??'null');if(remembered){if(config.apiBase){const session=await requestApi('/v1/me');user=session.user;personal=session.personal;}else{user=await storage.account(remembered.id);if(user)personal=await storage.personal(user.id);}}}catch{sessionStorage.removeItem('rt-user');}
render();observe();
if(document.modelContext?.registerTool){for(const tool of [
 {name:'read_rest_time_session',description:'Read the current Rest Time session timer and the two chart series.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({signedIn:Boolean(user),mode:route,workSeconds:personal?.sessionStarted?Math.floor((Date.now()-personal.sessionStarted)/1000):0,samples:personal?.samples??[]})},
 {name:'set_rest_time_view',description:'Switch an active focus session between full and minimal views.',inputSchema:{type:'object',properties:{mode:{type:'string',enum:['active','minimal']}},required:['mode'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async input=>{if(!input||!['active','minimal'].includes(input.mode))throw new Error('Invalid view.');if(!user||!personal.sessionStarted)throw new Error('Start a session first.');history.replaceState(null,'','#'+input.mode);render();return {mode:route};}},
]){try{await document.modelContext.registerTool(tool);}catch{}}}
